import type { Vendor } from "./types";

// Realistic mock data so the CRM demos well on first load. Seeded into
// localStorage once; after that the live store is the source of truth.
export const SEED_VENDORS: Vendor[] = [
  {
    id: "v-lumiere",
    name: "Lumière Photography",
    category: "photographer",
    contactName: "Ava Bennett",
    email: "hello@lumierephoto.com",
    phone: "(415) 555-0142",
    website: "https://lumierephoto.com",
    status: "booked",
    quoteAmount: 4800,
    depositAmount: 1200,
    depositDueDate: "2026-08-15",
    notes: "Loved their editorial style. Includes engagement shoot + album.",
    createdAt: "2026-06-28",
    log: [
      { id: "l1", type: "email", date: "2026-06-28", summary: "Sent inquiry with our date and venue." },
      { id: "l2", type: "call", date: "2026-07-02", summary: "Discussed packages — going with the full-day + album tier." },
      { id: "l3", type: "meeting", date: "2026-07-10", summary: "Coffee to review portfolio. Signed contract, deposit invoiced." },
    ],
  },
  {
    id: "v-rosewood",
    name: "Rosewood Estate",
    category: "venue",
    contactName: "Marcus Hale",
    email: "events@rosewoodestate.com",
    phone: "(707) 555-0188",
    website: "https://rosewoodestate.com",
    status: "quoted",
    quoteAmount: 18500,
    depositAmount: 5000,
    depositDueDate: "2026-08-01",
    notes: "Garden ceremony + barn reception. Holds 140. Waiting on final quote breakdown.",
    createdAt: "2026-06-20",
    log: [
      { id: "l1", type: "email", date: "2026-06-20", summary: "Requested availability for our weekend." },
      { id: "l2", type: "meeting", date: "2026-07-05", summary: "Site tour — loved the garden. Asked for itemized quote." },
      { id: "l3", type: "note", date: "2026-07-18", summary: "Quote received. Reviewing catering minimums before committing." },
    ],
  },
  {
    id: "v-bloom",
    name: "Bloom & Bramble",
    category: "florist",
    contactName: "Sofia Nguyen",
    email: "sofia@bloomandbramble.co",
    phone: "(510) 555-0119",
    website: "https://bloomandbramble.co",
    status: "contacted",
    quoteAmount: undefined,
    notes: "Wildflower / garden aesthetic. Seasonal peonies in range for our date.",
    createdAt: "2026-07-08",
    log: [
      { id: "l1", type: "email", date: "2026-07-08", summary: "Sent mood board and color palette." },
      { id: "l2", type: "email", date: "2026-07-14", summary: "They replied — available, asked for our budget range." },
    ],
  },
  {
    id: "v-harvest",
    name: "Harvest Table Catering",
    category: "caterer",
    contactName: "Dana Ortiz",
    email: "book@harvesttable.com",
    phone: "(415) 555-0177",
    website: "https://harvesttable.com",
    status: "quoted",
    quoteAmount: 11200,
    depositAmount: 2800,
    depositDueDate: "2026-08-20",
    notes: "Farm-to-table, family-style. $80/head for 140. Tasting scheduled.",
    createdAt: "2026-07-01",
    log: [
      { id: "l1", type: "call", date: "2026-07-01", summary: "Initial call — walked through menu options." },
      { id: "l2", type: "email", date: "2026-07-12", summary: "Received formal quote for 140 guests." },
      { id: "l3", type: "meeting", date: "2026-07-25", summary: "Tasting booked at their kitchen." },
    ],
  },
  {
    id: "v-lantern",
    name: "Lantern Sound DJs",
    category: "music",
    contactName: "Theo Park",
    email: "theo@lanternsound.dj",
    phone: "(628) 555-0165",
    website: "https://lanternsound.dj",
    status: "lead",
    notes: "Recommended by Lumière. Haven't reached out yet.",
    createdAt: "2026-07-19",
    log: [],
  },
  {
    id: "v-gilded",
    name: "Gilded Events Co.",
    category: "planner",
    contactName: "Priya Raman",
    email: "priya@gildedevents.co",
    phone: "(415) 555-0102",
    website: "https://gildedevents.co",
    status: "declined",
    quoteAmount: 9500,
    notes: "Full-service planning out of budget. Keeping day-of coordination as an option.",
    createdAt: "2026-06-15",
    log: [
      { id: "l1", type: "call", date: "2026-06-15", summary: "Intro call about full-service planning." },
      { id: "l2", type: "email", date: "2026-06-22", summary: "Quote came in over budget — passing for now." },
    ],
  },
];

export const SEED_BUDGET = 45000;
